
My goal here
is to use historical tables
from the ICTV,
eventually via a dedicated R package,
and maybe even using lazyloading of R-data objects.

Historical Excel files
can be downloaded in bulk
from https://ictv.global/msl
(check the box at the top
 to select all versions.)
Move downloaded versions of the MSL
to inst/extdata/
and remove the minor-update versions
with the shell script in that directory
to get a 1-per-year set.

```{r, warning=FALSE}
library(readxl)
library(dplyr)

years <- 
  substring(dir("inst/extdata", pattern = "xls"),
            26, 29)
msl_files <- dir("inst/extdata", pattern = "xls", full.names = TRUE)

## Defer MSL numbers.  Could add MSL 33 (2018a) back.
## See https://ictv.global/taxonomy/history
#msl_nums <- c(23:32, 34:38)

num_msl <- length(msl_files)
ictv_msl_list <- vector("list", num_msl)
#' excel_sheets(msl_files[num_msl])
#' for (i in 1:num_msl)  { print(i);  print(excel_sheets(msl_files[i])) }

#' First sheet relevant
ictv_msl_list[[2]] <- read_excel(msl_files[2])

#' Second sheet relevant
for (i in c(1, 3:6, 15:16)) {
  ictv_msl_list[[i]] <- read_excel(msl_files[i], sheet = 2,
                                   .name_repair = "universal")
}

for (i in c(7:14)) {
  ictv_msl_list[[i]] <- read_excel(msl_files[i], sheet = 3,
                                   .name_repair = "universal")
}

## How should we check this?
## Look at one large genus to start.
begomo_list <- vector("list", num_msl)
num_begomo_spp <- vector(length = num_msl)
sweepo_list <- vector("list", num_msl)
num_sweepo_spp <- vector(length = num_msl)

for (i in 1:num_msl) {
  begomo_list[[i]] <- filter(ictv_msl_list[[i]],
                             Genus == "Begomovirus")
  num_begomo_spp[i] <- nrow(begomo_list[[i]])
  sweepo_list[[i]] <- filter(ictv_msl_list[[i]],
                             grepl("Sweet potato|Ipomoea", Species),
                             Genus == "Begomovirus")
  num_sweepo_spp[i] <- nrow(sweepo_list[[i]])
}

cbind(years, num_begomo_spp, num_sweepo_spp)
```
Searching with a text string, as above,
fails after species were renamed.

## Possible more-refined approaches to the history of the taxonomy
Others have considered using one or more R packages
to access the full history of the taxonomy,
including taxon merging, splitting, reassignment-moves, and renaming
(taxa package [issue 136](https://github.com/ropensci/taxa/issues/136)
 and linked taxize issue 695).
 